version: 2
jobs: 
  build: 
    macos:
      xcode: "10.2.1"
    steps:
      - checkout
      - run:
          name: Installing Pods...
          command: pod install
      - run:
          name: Decoding Mac Developer Certificate...
          command: fastlane prepare_certificates  
      - run:
          name: Building Pock...
          command: xcodebuild -workspace Pock.xcworkspace -scheme Pock
